import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseGuide, validateFrontmatter } from '../../lib/guide-validation.ts';
import { TfjsEmbedder } from '../lib/tfjs-embedder.ts';
import { type UseCaseEntry, readEmbeddingsBlob, writeEmbeddingsBlob } from '../lib/corpus-io.ts';

export type { UseCaseEntry };
export { readEmbeddingsBlob, writeEmbeddingsBlob };

export interface BuildResult {
  numUseCases: number;
  vectorDim: number;
  guides: number;
  numTags: number;
}

export interface BuildOptions {
  guidesDir: string;
  outDir: string;
}

export async function buildGuides(opts: BuildOptions): Promise<BuildResult> {
  const guidePaths = collectGuidePaths(opts.guidesDir);
  const embedder = new TfjsEmbedder();

  // First pass: parse + validate guides; collect tags.
  const parsedGuides: Array<{ fm: ReturnType<typeof validateFrontmatter>; useCases: string[]; description: string; tags: string[] }> = [];
  const allTags = new Set<string>();
  for (const guidePath of guidePaths) {
    const src = await fs.promises.readFile(guidePath, 'utf8');
    const { frontmatter } = parseGuide(src);
    const fm = validateFrontmatter(frontmatter);
    parsedGuides.push({ fm, useCases: fm.useCases, description: fm.description, tags: fm.tags });
    for (const t of fm.tags) allTags.add(t);
  }

  // Build tag index + embeddings.
  const sortedTags = Array.from(allTags).sort();
  const tagIndex: Record<string, number> = {};
  sortedTags.forEach((t, i) => { tagIndex[t] = i; });
  const tagVectors: Float32Array[] = [];
  for (const tag of sortedTags) {
    // Embed the tag's NAME — agents query in natural language, tag names are kebab-case English phrases.
    // Replace hyphens with spaces so the model treats "tier-progression" as "tier progression."
    const tagText = tag.replace(/-/g, ' ');
    tagVectors.push(await embedder.embed(tagText));
  }

  // Second pass: build use-case entries with tagIndices resolved.
  const entries: UseCaseEntry[] = [];
  const useCaseVectors: Float32Array[] = [];
  for (const g of parsedGuides) {
    const tagIndices = g.tags.map(t => tagIndex[t]).filter((i): i is number => i !== undefined);
    for (const useCase of g.useCases) {
      const idx = entries.length;
      entries.push({
        id: g.fm.id,
        category: g.fm.category,
        description: g.description,
        useCase,
        embeddingIndex: idx,
        tagIndices,
      });
      useCaseVectors.push(await embedder.embed(`${useCase}. ${g.description}`));
    }
  }

  const vectorDim = useCaseVectors[0]?.length ?? 384;

  await fs.promises.mkdir(opts.outDir, { recursive: true });
  await writeUseCases(path.join(opts.outDir, 'use-cases.gen.ts'), entries);
  await writeEmbeddingsBlob(path.join(opts.outDir, 'embeddings.gen.bin'), useCaseVectors, vectorDim);

  // Write tag artifacts.
  await writeTagIndex(path.join(opts.outDir, 'tag-index.gen.ts'), tagIndex);
  await writeEmbeddingsBlob(path.join(opts.outDir, 'tag-embeddings.gen.bin'), tagVectors, vectorDim);

  return { numUseCases: entries.length, vectorDim, guides: guidePaths.length, numTags: sortedTags.length };
}

function collectGuidePaths(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const out: string[] = [];
  function walk(d: string) {
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile() && entry.name === 'guide.md') out.push(full);
    }
  }
  walk(dir);
  return out.sort();
}

async function writeUseCases(outPath: string, entries: UseCaseEntry[]): Promise<void> {
  const header = `// AUTO-GENERATED by serving/scripts/build-guides.ts. Do not edit by hand.\n` +
                 `import type { UseCaseEntry } from '../lib/corpus-io.ts';\n\n` +
                 `export const USE_CASES: ReadonlyArray<UseCaseEntry> = [\n`;
  const body = entries.map(e =>
    `  { id: ${JSON.stringify(e.id)}, ` +
    `category: ${JSON.stringify(e.category)}, ` +
    `description: ${JSON.stringify(e.description)}, ` +
    `useCase: ${JSON.stringify(e.useCase)}, ` +
    `embeddingIndex: ${e.embeddingIndex}, ` +
    `tagIndices: [${e.tagIndices.join(', ')}] },`,
  ).join('\n');
  const footer = `\n];\n`;
  await fs.promises.writeFile(outPath, header + body + footer);
}

async function writeTagIndex(outPath: string, tagIndex: Record<string, number>): Promise<void> {
  const lines = Object.keys(tagIndex).sort().map(t => `  ${JSON.stringify(t)}: ${tagIndex[t]},`);
  const content = `// AUTO-GENERATED by serving/scripts/build-guides.ts.\n\n` +
                  `export const TAG_INDEX: Readonly<Record<string, number>> = {\n` +
                  `${lines.join('\n')}\n` +
                  `};\n\n` +
                  `export const TAGS: ReadonlyArray<string> = Object.keys(TAG_INDEX);\n`;
  await fs.promises.writeFile(outPath, content);
}

// CLI entry: when invoked directly, build from the workspace's guides/ into serving/lib/.
const __filename = fileURLToPath(import.meta.url);
if (process.argv[1] === __filename) {
  const servingDir = path.resolve(path.dirname(__filename), '..');
  const rootDir = path.resolve(servingDir, '..');
  const guidesDir = path.join(rootDir, 'guides');
  const outDir = path.join(servingDir, 'lib');
  const result = await buildGuides({ guidesDir, outDir });
  console.log(`Built ${result.numUseCases} use cases from ${result.guides} guide(s) into ${outDir}, ${result.numTags} tags`);
}
