import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseGuide, validateFrontmatter, type GuideFrontmatter } from '../../lib/guide-validation.ts';
import { TfjsEmbedder } from '../lib/tfjs-embedder.ts';

export interface UseCaseEntry {
  id: string;                  // guide id
  category: GuideFrontmatter['category'];
  description: string;          // guide-level description
  useCase: string;              // one of the guide's useCases entries
  embeddingIndex: number;       // row index into embeddings.gen.bin
}

export interface BuildResult {
  numUseCases: number;
  vectorDim: number;
  guides: number;
}

export interface BuildOptions {
  guidesDir: string;
  outDir: string;
}

export async function buildGuides(opts: BuildOptions): Promise<BuildResult> {
  const guidePaths = collectGuidePaths(opts.guidesDir);
  const embedder = new TfjsEmbedder();
  const entries: UseCaseEntry[] = [];
  const vectors: Float32Array[] = [];

  for (const guidePath of guidePaths) {
    const src = await fs.promises.readFile(guidePath, 'utf8');
    const { frontmatter } = parseGuide(src);
    const fm = validateFrontmatter(frontmatter);

    for (const useCase of fm.useCases) {
      const idx = entries.length;
      entries.push({
        id: fm.id,
        category: fm.category,
        description: fm.description,
        useCase,
        embeddingIndex: idx,
      });
      // Embed (description + useCase) for better semantic match.
      const vec = await embedder.embed(`${useCase}. ${fm.description}`);
      vectors.push(vec);
    }
  }

  const vectorDim = vectors[0]?.length ?? 384;

  await fs.promises.mkdir(opts.outDir, { recursive: true });
  await writeUseCases(path.join(opts.outDir, 'use-cases.gen.ts'), entries);
  await writeEmbeddingsBlob(path.join(opts.outDir, 'embeddings.gen.bin'), vectors, vectorDim);

  return { numUseCases: entries.length, vectorDim, guides: guidePaths.length };
}

function collectGuidePaths(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const out: string[] = [];
  function walk(d: string) {
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile() && entry.name === 'guide.md') out.push(full);
    }
  }
  walk(dir);
  return out.sort();
}

async function writeUseCases(outPath: string, entries: UseCaseEntry[]): Promise<void> {
  const header = `// AUTO-GENERATED by serving/scripts/build-guides.ts. Do not edit by hand.\n` +
                 `import type { UseCaseEntry } from '../scripts/build-guides.ts';\n\n` +
                 `export const USE_CASES: ReadonlyArray<UseCaseEntry> = [\n`;
  const body = entries.map(e =>
    `  { id: ${JSON.stringify(e.id)}, ` +
    `category: ${JSON.stringify(e.category)}, ` +
    `description: ${JSON.stringify(e.description)}, ` +
    `useCase: ${JSON.stringify(e.useCase)}, ` +
    `embeddingIndex: ${e.embeddingIndex} },`,
  ).join('\n');
  const footer = `\n];\n`;
  await fs.promises.writeFile(outPath, header + body + footer);
}

async function writeEmbeddingsBlob(outPath: string, vectors: Float32Array[], vectorDim: number): Promise<void> {
  const header = Buffer.alloc(8);
  header.writeUInt32LE(vectors.length, 0);
  header.writeUInt32LE(vectorDim, 4);
  const bodyBytes = vectors.length * vectorDim * 4;
  const body = Buffer.alloc(bodyBytes);
  let off = 0;
  for (const vec of vectors) {
    for (let i = 0; i < vectorDim; i++) {
      body.writeFloatLE(vec[i], off);
      off += 4;
    }
  }
  await fs.promises.writeFile(outPath, Buffer.concat([header, body]));
}

export function readEmbeddingsBlob(filePath: string): {
  numVectors: number;
  vectorDim: number;
  vectors: Float32Array[];
} {
  const buf = fs.readFileSync(filePath);
  const numVectors = buf.readUInt32LE(0);
  const vectorDim = buf.readUInt32LE(4);
  const vectors: Float32Array[] = [];
  let off = 8;
  for (let v = 0; v < numVectors; v++) {
    const arr = new Float32Array(vectorDim);
    for (let i = 0; i < vectorDim; i++) {
      arr[i] = buf.readFloatLE(off);
      off += 4;
    }
    vectors.push(arr);
  }
  return { numVectors, vectorDim, vectors };
}

// CLI entry: when invoked directly, build from the workspace's guides/ into serving/lib/.
const __filename = fileURLToPath(import.meta.url);
if (process.argv[1] === __filename) {
  const servingDir = path.resolve(path.dirname(__filename), '..');
  const rootDir = path.resolve(servingDir, '..');
  const guidesDir = path.join(rootDir, 'guides');
  const outDir = path.join(servingDir, 'lib');
  const result = await buildGuides({ guidesDir, outDir });
  console.log(`Built ${result.numUseCases} use cases from ${result.guides} guide(s) into ${outDir}`);
}
