// AUTO-GENERATED by serving/scripts/build-guides.ts. Do not edit by hand.
import type { UseCaseEntry } from '../scripts/build-guides.ts';

export const USE_CASES: ReadonlyArray<UseCaseEntry> = [
  { id: "new-input-system-basics", category: "unity-engine", description: "Use Unity's Input System package over the legacy Input Manager for keyboard, mouse, gamepad, and touch handling.", useCase: "read player input in Unity", embeddingIndex: 0 },
  { id: "new-input-system-basics", category: "unity-engine", description: "Use Unity's Input System package over the legacy Input Manager for keyboard, mouse, gamepad, and touch handling.", useCase: "handle keyboard input in Unity", embeddingIndex: 1 },
  { id: "new-input-system-basics", category: "unity-engine", description: "Use Unity's Input System package over the legacy Input Manager for keyboard, mouse, gamepad, and touch handling.", useCase: "handle gamepad input in Unity", embeddingIndex: 2 },
  { id: "new-input-system-basics", category: "unity-engine", description: "Use Unity's Input System package over the legacy Input Manager for keyboard, mouse, gamepad, and touch handling.", useCase: "replace legacy Input.GetKey with new Input System", embeddingIndex: 3 },
  { id: "new-input-system-basics", category: "unity-engine", description: "Use Unity's Input System package over the legacy Input Manager for keyboard, mouse, gamepad, and touch handling.", useCase: "set up Input Actions in Unity", embeddingIndex: 4 },
];
